config/routes.rb
Blazer::Engine.routes.draw do
  resources :queries do
    post :run, on: :collection # err on the side of caution
    post :refresh, on: :member
    get :tables, on: :collection
  end
  resources :checks, except: [:show] do
    get :run, on: :member
  end
  resources :dashboards do
    post :refresh, on: :member
  end
  root to: "queries#home"
end

app/models/blazer/audit.rb
module Blazer
  class Audit < ActiveRecord::Base
    belongs_to :user, Blazer::BELONGS_TO_OPTIONAL.merge(class_name: Blazer.user_class.to_s)
    belongs_to :query, Blazer::BELONGS_TO_OPTIONAL
  end
end

app/models/blazer/check.rb
module Blazer
  class Check < ActiveRecord::Base
    belongs_to :creator, Blazer::BELONGS_TO_OPTIONAL.merge(class_name: Blazer.user_class.to_s) if Blazer.user_class
    belongs_to :query

    validates :query_id, presence: true

    before_validation :set_state

    def set_state
      self.state ||= "new"
    end

    def split_emails
      emails.to_s.downcase.split(",").map(&:strip)
    end

    def update_state(result)
      check_type =
        if respond_to?(:check_type)
          self.check_type
        elsif respond_to?(:invert)
          invert ? "missing_data" : "bad_data"
        else
          "bad_data"
        end

      message = result.error

      self.state =
        if result.timed_out?
          "timed out"
        elsif result.error
          "error"
        elsif check_type == "anomaly"
          anomaly, message = result.detect_anomaly
          if anomaly.nil?
            "error"
          elsif anomaly
            "failing"
          else
            "passing"
          end
        elsif result.rows.any?
          check_type == "missing_data" ? "passing" : "failing"
        else
          check_type == "missing_data" ? "failing" : "passing"
        end

      self.last_run_at = Time.now if respond_to?(:last_run_at=)
      self.message = message if respond_to?(:message=)

      if respond_to?(:timeouts=)
        if result.timed_out?
          self.timeouts += 1
          self.state = "disabled" if timeouts >= 3
        else
          self.timeouts = 0
        end
      end

      # do not notify on creation, except when not passing
      if (state_was != "new" || state != "passing") && state != state_was && emails.present?
        Blazer::CheckMailer.state_change(self, state, state_was, result.rows.size, message).deliver_later
      end
      save! if changed?
    end
  end
end

app/models/blazer/connection.rb
module Blazer
  class Connection < ActiveRecord::Base
    self.abstract_class = true
  end
end

app/models/blazer/dashboard.rb
module Blazer
  class Dashboard < ActiveRecord::Base
    belongs_to :creator, Blazer::BELONGS_TO_OPTIONAL.merge(class_name: Blazer.user_class.to_s) if Blazer.user_class
    has_many :dashboard_queries, dependent: :destroy
    has_many :queries, through: :dashboard_queries

    validates :name, presence: true

    def to_param
      [id, name.gsub("'", "").parameterize].join("-")
    end
  end
end

app/models/blazer/dashboard_query.rb
module Blazer
  class DashboardQuery < ActiveRecord::Base
    belongs_to :dashboard
    belongs_to :query

    validates :dashboard_id, presence: true
    validates :query_id, presence: true
  end
end

app/models/blazer/query.rb
module Blazer
  class Query < ActiveRecord::Base
    belongs_to :creator, Blazer::BELONGS_TO_OPTIONAL.merge(class_name: Blazer.user_class.to_s) if Blazer.user_class
    has_many :checks, dependent: :destroy
    has_many :dashboard_queries, dependent: :destroy
    has_many :dashboards, through: :dashboard_queries
    has_many :audits

    validates :statement, presence: true

    scope :named, -> { where("name <> ''") }

    def to_param
      [id, name].compact.join("-").gsub("'", "").parameterize
    end

    def friendly_name
      name.to_s.gsub(/\[.+\]/, "").strip
    end

    def editable?(user)
      (name.present? && name.first != "*") || user == creator
    end
  end
end

app/controllers/blazer/base_controller.rb
module Blazer
  class BaseController < ApplicationController
    # skip all filters
    skip_action_callback *_process_action_callbacks.map(&:filter)

    protect_from_forgery with: :exception

    if ENV["BLAZER_PASSWORD"]
      http_basic_authenticate_with name: ENV["BLAZER_USERNAME"], password: ENV["BLAZER_PASSWORD"]
    end

    if Blazer.before_action
      before_action Blazer.before_action
    end

    layout "blazer/application"

    private

    def process_vars(statement, data_source)
      (@bind_vars ||= []).concat(extract_vars(statement)).uniq!
      @bind_vars.each do |var|
        params[var] ||= Blazer.data_sources[data_source].variable_defaults[var]
      end
      @success = @bind_vars.all? { |v| params[v] }

      if @success
        @bind_vars.each do |var|
          value = params[var].presence
          if value
            if value =~ /\A\d+\z/
              value = value.to_i
            elsif value =~ /\A\d+\.\d+\z/
              value = value.to_f
            end
          end
          if var.end_with?("_at")
            value = Blazer.time_zone.parse(value) rescue nil
          end
          value.gsub!(" ", "+") if ["start_time", "end_time"].include?(var) # fix for Quip bug
          statement.gsub!("{#{var}}", ActiveRecord::Base.connection.quote(value))
        end
      end
    end

    def extract_vars(statement)
      # strip commented out lines
      # and regex {1} or {1,2}
      statement.gsub(/\-\-.+/, "").gsub(/\/\*.+\*\//m, "").scan(/\{.*?\}/).map { |v| v[1...-1] }.reject { |v| /\A\d+(\,\d+)?\z/.match(v) }.uniq
    end
    helper_method :extract_vars

    def variable_params
      params.except(:controller, :action, :id, :host, :query, :dashboard, :query_id, :query_ids, :table_names, :authenticity_token, :utf8, :_method, :commit, :statement, :data_source, :name, :fork_query_id, :blazer).permit!
    end
    helper_method :variable_params

    def blazer_user
      send(Blazer.user_method) if Blazer.user_method && respond_to?(Blazer.user_method)
    end
    helper_method :blazer_user
  end
end

app/controllers/blazer/checks_controller.rb
module Blazer
  class ChecksController < BaseController
    before_action :set_check, only: [:edit, :update, :destroy, :run]

    def index
      state_order = [nil, "disabled", "error", "timed out", "failing", "passing"]
      @checks = Blazer::Check.joins(:query).includes(:query).order("blazer_queries.name, blazer_checks.id").to_a.sort_by { |q| state_order.index(q.state) || 99 }
      @checks.select! { |c| "#{c.query.name} #{c.emails}".downcase.include?(params[:q]) } if params[:q]
    end

    def new
      @check = Blazer::Check.new(query_id: params[:query_id])
    end

    def create
      @check = Blazer::Check.new(check_params)
      # use creator_id instead of creator
      # since we setup association without checking if column exists
      @check.creator = blazer_user if @check.respond_to?(:creator_id=) && blazer_user

      if @check.save
        redirect_to run_check_path(@check)
      else
        render :new
      end
    end

    def update
      if @check.update(check_params)
        redirect_to run_check_path(@check)
      else
        render :edit
      end
    end

    def destroy
      @check.destroy
      redirect_to checks_path
    end

    def run
      @query = @check.query
      redirect_to query_path(@query)
    end

    private

    def check_params
      params.require(:check).permit(:query_id, :emails, :invert, :check_type, :schedule)
    end

    def set_check
      @check = Blazer::Check.find(params[:id])
    end
  end
end

app/controllers/blazer/dashboards_controller.rb
module Blazer
  class DashboardsController < BaseController
    before_action :set_dashboard, only: [:show, :edit, :update, :destroy, :refresh]

    def index
      @dashboards = Blazer::Dashboard.order(:name)
    end

    def new
      @dashboard = Blazer::Dashboard.new
    end

    def create
      @dashboard = Blazer::Dashboard.new
      # use creator_id instead of creator
      # since we setup association without checking if column exists
      @dashboard.creator = blazer_user if @dashboard.respond_to?(:creator_id=) && blazer_user

      if update_dashboard(@dashboard)
        redirect_to dashboard_path(@dashboard)
      else
        render :new
      end
    end

    def show
      @queries = @dashboard.dashboard_queries.order(:position).preload(:query).map(&:query)
      @queries.each do |query|
        process_vars(query.statement, query.data_source)
      end
      @bind_vars ||= []

      @smart_vars = {}
      @sql_errors = []
      @data_sources = @queries.map { |q| Blazer.data_sources[q.data_source] }.uniq
      @bind_vars.each do |var|
        @data_sources.each do |data_source|
          query = data_source.smart_variables[var]
          if query
            result = data_source.run_statement(query)
            ((@smart_vars[var] ||= []).concat(result.rows.map { |v| v.reverse })).uniq!
            @sql_errors << result.error if result.error
          end
        end
      end
    end

    def edit
    end

    def update
      if update_dashboard(@dashboard)
        redirect_to dashboard_path(@dashboard, variable_params)
      else
        render :edit
      end
    end

    def destroy
      @dashboard.destroy
      redirect_to dashboards_path
    end

    def refresh
      @dashboard.queries.each do |query|
        data_source = Blazer.data_sources[query.data_source]
        statement = query.statement.dup
        process_vars(statement, query.data_source)
        Blazer.transform_statement.call(data_source, statement) if Blazer.transform_statement
        data_source.clear_cache(statement)
      end
      redirect_to dashboard_path(@dashboard, variable_params)
    end

    protected

    def dashboard_params
      params.require(:dashboard).permit(:name)
    end

    def set_dashboard
      @dashboard = Blazer::Dashboard.find(params[:id])
    end

    def update_dashboard(dashboard)
      dashboard.assign_attributes(dashboard_params)
      Blazer::Dashboard.transaction do
        if params[:query_ids].is_a?(Array)
          query_ids = params[:query_ids].map(&:to_i)
          @queries = Blazer::Query.find(query_ids).sort_by { |q| query_ids.index(q.id) }
        end
        if dashboard.save
          if @queries
            @queries.each_with_index do |query, i|
              dashboard_query = dashboard.dashboard_queries.where(query_id: query.id).first_or_initialize
              dashboard_query.position = i
              dashboard_query.save!
            end
            if dashboard.persisted?
              dashboard.dashboard_queries.where.not(query_id: query_ids).destroy_all
            end
          end
          true
        end
      end
    end
  end
end

app/helpers/blazer/base_helper.rb
module Blazer
  module BaseHelper
    def blazer_title(title = nil)
      if title
        content_for(:title) { title }
      else
        content_for?(:title) ? content_for(:title) : nil
      end
    end

    BLAZER_URL_REGEX = /\Ahttps?:\/\/[\S]+\z/
    BLAZER_IMAGE_EXT = %w[png jpg jpeg gif]

    def blazer_format_value(key, value)
      if value.is_a?(Integer) && !key.to_s.end_with?("id")
        number_with_delimiter(value)
      elsif value =~ BLAZER_URL_REGEX
        # see if image or link
        if Blazer.images && (key.include?("image") || BLAZER_IMAGE_EXT.include?(value.split(".").last.split("?").first.try(:downcase)))
          link_to value, target: "_blank" do
            image_tag value, referrerpolicy: "no-referrer"
          end
        else
          link_to value, value, target: "_blank"
        end
      else
        value
      end
    end

    def blazer_maps?
      ENV["MAPBOX_ACCESS_TOKEN"].present?
    end

    JSON_ESCAPE = { '&' => '\u0026', '>' => '\u003e', '<' => '\u003c', "\u2028" => '\u2028', "\u2029" => '\u2029' }
    JSON_ESCAPE_REGEXP = /[\u2028\u2029&><]/u

    # Prior to version 4.1 of rails double quotes were inadventently removed in json_escape.
    # This adds the correct json_escape functionality to rails versions < 4.1
    def blazer_json_escape(s)
      if Rails::VERSION::STRING < "4.1"
        result = s.to_s.gsub(JSON_ESCAPE_REGEXP, JSON_ESCAPE)
        s.html_safe? ? result.html_safe : result
      else
        json_escape(s)
      end
    end
  end
end

app/views/blazer/dashboards/_form.html.erb
<% if @dashboard.errors.any? %>
  <div class="alert alert-danger"><%= @dashboard.errors.full_messages.first %></div>
<% end %>

<style>
.glyphicon-remove {
  cursor: pointer;
  color: #d9534f;
  display: none;
}

li:hover .glyphicon-remove {
  display: inline;
}

.list-group {
  cursor: move;
}
</style>

<%= form_for @dashboard, url: (@dashboard.persisted? ? dashboard_path(@dashboard, variable_params) : dashboards_path(variable_params)) do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="form-group <%= "hide" if (@queries || @dashboard.queries).empty? %>">
    <%= f.label :charts %>
    <ul class="list-group">
      <% (@queries || @dashboard.dashboard_queries.order(:position).map(&:query)).each do |query| %>
        <li class="list-group-item">
          <span class="glyphicon glyphicon-remove" aria-hidden="true" style="float: right; margin-top: 3px;"></span>
          <%= query.name %>
          <%= hidden_field_tag "query_ids[]", query.id %>
        </li>
      <% end %>
    </ul>
  </div>
  <div class="form-group">
    <%= f.label :query_id, "Add Chart" %>
    <div class="hide">
      <%= select_tag :query_id, nil, {include_blank: true, placeholder: "Select chart"} %>
    </div>
    <script>
      var queries = <%= blazer_json_escape(Blazer::Query.named.order(:name).select("id, name").map { |q| {text: q.name, value: q.id} }.to_json).html_safe %>;
      $("#query_id").selectize({options: queries, highlight: false, maxOptions: 100}).parents(".hide").removeClass("hide");
      $("#query_id").change( function () {
        var $option = $(this).find("option:selected");
        if ($option.val() !== "") {
          var $li = $("<li></li>");
          $li.addClass("list-group-item");
          $li.text($option.text());
          $li.prepend('<span class="glyphicon glyphicon-remove" aria-hidden="true" style="float: right; margin-top: 3px;"></span><input type="hidden" name="query_ids[]" id="query_ids_" value="' + $option.val() + '">');
          $(".list-group").append($li);
          $(this)[0].selectize.setValue("");
          $(".form-group").removeClass("hide");
        }
      });
    </script>
  </div>
  <p>
    <% if @dashboard.persisted? %>
      <%= link_to "Delete", dashboard_path(@dashboard), method: :delete, "data-confirm" => "Are you sure?", class: "btn btn-danger" %>
    <% end %>
    <%= f.submit "Save", class: "btn btn-success" %>
  </p>
<% end %>

<script>
  $(".list-group").on("click", ".glyphicon-remove", function () {
    $(this).parents("li:first").remove();
  });
  Sortable.create($(".list-group").get(0));

  // $("form").submit( function () {
  //   var query_ids = $("li").map( function () {
  //     return $(this).attr("data-query-id");
  //   });
  //   console.log(query_ids.join(","));
  //   return false;
  // });

  // var editableList = Sortable.create($(".list-group").get(0), {
  //   filter: '.js-remove',
  //   onFilter: function (evt) {
  //     var el = editableList.closest(evt.item); // get dragged item
  //     el && el.parentNode.removeChild(el);
  //   }
  // });
</script>

app/views/blazer/dashboards/edit.html.erb
<%= render partial: "form" %>

app/views/blazer/dashboards/index.html.erb
<% blazer_title "Dashboards" %>

<p style="float: right;"><%= link_to "New Dashboard", new_dashboard_path, class: "btn btn-info" %></p>
<%= render partial: "blazer/nav" %>

<table class="table">
  <thead>
    <tr>
      <th>Dashboard</th>
    </tr>
  </thead>
  <tbody>
    <% @dashboards.each do |dashboard| %>
      <tr>
        <td><%= link_to dashboard.name, dashboard %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/blazer/dashboards/new.html.erb
<%= render partial: "form" %>

app/views/blazer/dashboards/show.html.erb
<% blazer_title @dashboard.name %>

<script>
  function submitIfCompleted($form) {
    var completed = true;
    $form.find("input[name], select").each( function () {
      if ($(this).val() == "") {
        completed = false;
      }
    });
    if (completed) {
      $form.submit();
    }
  }
</script>

<div style="position: fixed; top: 0; left: 0; right: 0; background-color: whitesmoke; height: 60px; z-index: 1001;">
  <div class="container">
    <div class="row" style="padding-top: 13px;">
      <div class="col-sm-9">
        <%= render partial: "blazer/nav" %>
        <h3 style="margin: 0; line-height: 34px; display: inline;">
          <%= @dashboard.name %>
        </h3>
      </div>
      <div class="col-sm-3 text-right">
        <%= link_to "Edit", edit_dashboard_path(@dashboard, variable_params), class: "btn btn-info" %>
      </div>
    </div>
  </div>
</div>

<div style="margin-bottom: 60px;"></div>

<% if @data_sources.any? { |ds| ds.cache_mode != "off" } %>
  <p class="text-muted" style="float: right;">
    Some queries may be cached
    <%= link_to "Refresh", refresh_dashboard_path(@dashboard, variable_params), method: :post %>
  </p>
<% end %>

<% if @bind_vars.any? %>
  <form id="bind" method="get" action="<%= dashboard_path(@dashboard, variable_params) %>" class="form-inline" style="margin-bottom: 10px;">
    <% date_vars = ["start_time", "end_time"] %>
    <% if (date_vars - @bind_vars).empty? %>
      <% @bind_vars = @bind_vars - date_vars %>
    <% else %>
      <% date_vars = nil %>
    <% end %>

    <% @bind_vars.each_with_index do |var, i| %>
      <%= label_tag var, var %>
      <% if (data = @smart_vars[var]) %>
        <%= select_tag var, options_for_select([[nil, nil]] + data, selected: params[var]), style: "margin-right: 20px; width: 200px; display: none;" %>
        <script>
          $("#<%= var %>").selectize({
            create: true
          });
        </script>
      <% else %>
        <%= text_field_tag var, params[var], style: "width: 120px; margin-right: 20px;", autofocus: i == 0 && !var.end_with?("_at") && !params[var], class: "form-control" %>
        <% if var.end_with?("_at") %>
          <script>
            $("#<%= var %>").daterangepicker({singleDatePicker: true, locale: {format: "YYYY-MM-DD"}});
          </script>
        <% end %>
      <% end %>
    <% end %>

    <% if date_vars %>
      <% date_vars.each do |var| %>
        <%= hidden_field_tag var, params[var] %>
      <% end %>

      <%= label_tag nil, date_vars.join(" & ") %>
      <div class="selectize-control single" style="width: 300px;">
        <div id="reportrange" class="selectize-input" style="display: inline-block;">
          <span>Select a time range</span>
        </div>
      </div>

      <script>
        var timeZone = "<%= Blazer.time_zone.tzinfo.name %>";
        var format = "YYYY-MM-DD";
        var now = moment.tz(timeZone);

        function dateStr(daysAgo) {
          return now.clone().subtract(daysAgo || 0, "days").format(format);
        }

        function toDate(time) {
          return moment.tz(time.format(format), timeZone);
        }

        function setTimeInputs(start, end) {
          $("#start_time").val(toDate(start).utc().format());
          $("#end_time").val(toDate(end).endOf("day").utc().format());
        }

        $('#reportrange').daterangepicker(
          {
            ranges: {
             "Today": [dateStr(), dateStr()],
             "Last 7 Days": [dateStr(6), dateStr()],
             "Last 30 Days": [dateStr(29), dateStr()]
            },
            locale: {
              format: format
            },
            startDate: dateStr(29),
            endDate: dateStr(),
            opens: "left"
          },
          function(start, end) {
            setTimeInputs(start, end);
            submitIfCompleted($("#start_time").closest("form"));
          }
        ).on('apply.daterangepicker', function(ev, picker) {
          setTimeInputs(picker.startDate, picker.endDate);
          $('#reportrange span').html(toDate(picker.startDate).format('MMMM D, YYYY') + ' - ' + toDate(picker.endDate).format('MMMM D, YYYY'));
        })

        if ($("#start_time").val().length > 0) {
          var picker = $("#reportrange").data('daterangepicker');
          picker.setStartDate(moment.tz($("#start_time").val(), timeZone));
          picker.setEndDate(moment.tz($("#end_time").val(), timeZone));
          $("#reportrange").trigger('apply.daterangepicker', picker)
        } else {
          var picker = $("#reportrange").data('daterangepicker');
          $("#reportrange").trigger('apply.daterangepicker', picker);
          submitIfCompleted($("#start_time").closest("form"));
        }
      </script>
    <% end %>
  </form>
<% end %>

<% @queries.each_with_index do |query, i| %>
  <div style="padding-top: 10px; clear: both;">
    <h4 style="text-align: center;"><%= link_to query.friendly_name, query_path(query, variable_params), target: "_blank", style: "color: inherit;" %></h4>
    <div id="chart-<%= i %>" class="chart">
      <p class="text-muted">Loading...</p>
    </div>
  </div>
  <script>
    var data = <%= blazer_json_escape({statement: query.statement, query_id: query.id, only_chart: true}.to_json).html_safe %>;

    runQuery(data, function (data) {
      $("#chart-<%= i %>").html(data);
      $("#chart-<%= i %> table").stupidtable();
    }, function (message) {
      $("#chart-<%= i %>").css("color", "red").html(message);
    });
  </script>
<% end %>

<script>
  $(".form-inline input, .form-inline select").change( function () {
    submitIfCompleted($(this).closest("form"));
  });
</script>